name: Build PrismLauncher x86

on:
  push:
    branches:
      - "7.2"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Windows x86
    runs-on: windows-2022

    env:
      INSTALL_DIR: "install"
      INSTALL_PORTABLE_DIR: "install-portable"
      BUILD_DIR: "build"

    steps:
      ##
      # PREPARE
      ##

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt 5.15.2 x86
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: "==3.3.*"
          py7zrversion: ">=0.20.2"
          version: "5.15.2"
          host: windows
          target: desktop
          arch: win32_msvc2019
          modules: ""
          cache: true

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022
          arch: amd64_x86

      ##
      # CONFIGURE
      ##

      - name: Configure CMake
        shell: powershell
        run: |
          cmake `
            -S . `
            -B $env:BUILD_DIR `
            -DCMAKE_INSTALL_PREFIX=$env:INSTALL_DIR `
            -DCMAKE_BUILD_TYPE=Release `
            -DENABLE_LTO=ON `
            -DLauncher_BUILD_PLATFORM=official `
            -DLauncher_QT_VERSION_MAJOR=5 `
            -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDLL" `
            -A Win32 `
            -DLauncher_FORCE_BUNDLED_LIBS=ON

      ##
      # BUILD
      ##

      - name: Build
        run: |
          cmake --build $env:BUILD_DIR --config Release

      ##
      # PACKAGE
      ##

      - name: Install
        run: |
          cmake --install $env:BUILD_DIR --config Release

      - name: Create portable package
        shell: powershell
        run: |
          cmake --install $env:BUILD_DIR `
            --prefix $env:INSTALL_PORTABLE_DIR `
            --component portable

      - name: Create manifests
        shell: powershell
        run: |
          Get-ChildItem $env:INSTALL_DIR -Recurse -File |
            ForEach-Object FullName |
            Resolve-Path -Relative |
            ForEach-Object { $_.TrimStart('.\') } |
            ForEach-Object { $_.TrimStart($env:INSTALL_DIR) } |
            ForEach-Object { $_.TrimStart('\') } |
            Out-File -FilePath "$env:INSTALL_DIR\manifest.txt"

          Get-ChildItem $env:INSTALL_PORTABLE_DIR -Recurse -File |
            ForEach-Object FullName |
            Resolve-Path -Relative |
            ForEach-Object { $_.TrimStart('.\') } |
            ForEach-Object { $_.TrimStart($env:INSTALL_PORTABLE_DIR) } |
            ForEach-Object { $_.TrimStart('\') } |
            Out-File -FilePath "$env:INSTALL_PORTABLE_DIR\manifest.txt"

      ##
      # INSTALLER
      ##

      - name: Create installer
        shell: powershell
        run: |
          Set-Location $env:INSTALL_DIR
          makensis -NOCD "$env:GITHUB_WORKSPACE\$env:BUILD_DIR\program_info\win_install.nsi"

      ##
      # UPLOAD
      ##

      - name: Upload Windows x86 package
        uses: actions/upload-artifact@v4
        with:
          name: PrismLauncher-x86
          path: |
            install/**
            install-portable/**
          if-no-files-found: error
          retention-days: 30

      - name: Upload Windows x86 installer
        uses: actions/upload-artifact@v4
        with:
          name: PrismLauncher-x86-installer
          path: install/PrismLauncher-Setup.exe
          if-no-files-found: error
          retention-days: 30
